import { appointments, emergencyCases, notifications, surgeries } from "@/lib/db/schema";
import {
  APPOINTMENT_REASONS,
  EMERGENCY_SCENARIOS,
  NOTIFICATION_SEEDS,
  SURGERY_CATALOG,
  TIME_SLOTS,
} from "./datasets";
import { createRng, deterministicUuid, pick } from "./ids";
import {
  daysFrom,
  hoursFrom,
  type SeedContext,
  type SeedCounts,
  type Tx,
} from "./types";

const pad3 = (n: number): string => String(n).padStart(3, "0");

/**
 * 150 appointments across every patient: 88 past (mostly Completed),
 * 12 today, 50 future (Scheduled/Confirmed mix). Count-compatible IDs
 * (APT-001…) keep the app's count-based numbering collision-free.
 */
export async function seedAppointments(
  tx: Tx,
  ctx: SeedContext
): Promise<SeedCounts> {
  const rng = createRng(0xa9971);
  const now = ctx.now;
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const plans = ctx.plans;

  const PAST = 88;
  const TODAY = 12;
  const FUTURE = 50;
  const total = PAST + TODAY + FUTURE;

  for (let i = 0; i < total; i++) {
    const plan = plans[i % plans.length];
    const appointmentId = `APT-${pad3(i + 1)}`;
    const slot = pick(rng, TIME_SLOTS);

    let date: Date;
    let status: string;
    if (i < PAST) {
      date = daysFrom(today, -1 - Math.floor(rng() * 59));
      status = rng() < 0.88 ? "Completed" : "Cancelled";
    } else if (i < PAST + TODAY) {
      date = today;
      const bucket = i - PAST;
      status =
        bucket < 6 ? "Completed" : bucket < 10 ? "Confirmed" : "Scheduled";
    } else {
      date = daysFrom(today, 1 + Math.floor(rng() * 44));
      const bucket = rng();
      status = bucket < 0.65 ? "Scheduled" : bucket < 0.9 ? "Confirmed" : "Cancelled";
    }

    const rows = await tx
      .insert(appointments)
      .values({
        id: deterministicUuid("appointment", appointmentId),
        appointmentId,
        patientId: ctx.patients.get(plan.patientId)!,
        doctorName: plan.attendingDoctor,
        department: plan.department,
        date,
        time: slot,
        type:
          i % 10 < 7 ? "Consultation" : i % 10 < 9 ? "Follow-up" : "Emergency",
        status,
        reason: pick(rng, APPOINTMENT_REASONS),
        notes: i % 4 === 0 ? "Demo appointment generated by the seed." : null,
        createdAt: daysFrom(date, -3),
        updatedAt: daysFrom(date, -3),
      })
      .onConflictDoUpdate({
        target: appointments.appointmentId,
        set: {
          patientId: ctx.patients.get(plan.patientId)!,
          doctorName: plan.attendingDoctor,
          department: plan.department,
          date,
          time: slot,
          type:
            i % 10 < 7 ? "Consultation" : i % 10 < 9 ? "Follow-up" : "Emergency",
          status,
          reason: pick(rng, APPOINTMENT_REASONS),
          updatedAt: new Date(),
        },
      })
      .returning({ id: appointments.id });

    ctx.appointments.set(appointmentId, rows[0].id);
    const list = ctx.appointmentsByPatient.get(plan.patientId) ?? [];
    list.push({
      appointmentId,
      id: rows[0].id,
      patientId: plan.patientId,
      status,
      date,
    });
    ctx.appointmentsByPatient.set(plan.patientId, list);
  }

  for (const list of ctx.appointmentsByPatient.values()) {
    list.sort((a, b) => a.date.getTime() - b.date.getTime());
  }

  return { appointments: total };
}

/** 18 emergency cases — 3 landing today, 15 spread over the last fortnight. */
export async function seedEmergency(
  tx: Tx,
  ctx: SeedContext
): Promise<SeedCounts> {
  const rng = createRng(0xe3e3e3);
  const now = ctx.now;
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const admittedPlans = ctx.plans.filter((p) => p.admitted && !p.discharged);
  const otherPlans = ctx.plans.filter((p) => !p.admitted);
  const emergencyDoctors = ["STF-008", "STF-007", "STF-006"];

  const total = 18;
  for (let i = 0; i < total; i++) {
    const caseId = `EMC-${pad3(i + 1)}`;
    const scenario = EMERGENCY_SCENARIOS[i % EMERGENCY_SCENARIOS.length];
    const isToday = i < 3;
    let arrivalTime = isToday
      ? hoursFrom(today, 10 + i * 2)
      : hoursFrom(daysFrom(now, -1 - Math.floor(rng() * 13)), 8 + Math.floor(rng() * 12));
    if (arrivalTime > now) {
      // Stay inside today for today's cases; never produce a future stamp.
      const floor = isToday ? today.getTime() + 5 * 60 * 1000 : now.getTime() - 60 * 60 * 1000;
      arrivalTime = new Date(Math.max(Math.min(arrivalTime.getTime(), now.getTime() - 5 * 60 * 1000), floor));
    }

    let status: string;
    if (isToday) {
      status = i === 0 ? "Waiting" : i === 1 ? "In Treatment" : "In Treatment";
    } else {
      const bucket = rng();
      status =
        bucket < 0.5
          ? "Discharged"
          : bucket < 0.7
            ? "Admitted"
            : "In Treatment";
    }

    // "Admitted" cases must point at actually-admitted patients.
    const pool = status === "Admitted" ? admittedPlans : i % 3 === 0 ? admittedPlans : otherPlans.length > 0 ? otherPlans : admittedPlans;
    const plan = pool[i % pool.length];
    const doctorStaffId = emergencyDoctors[i % emergencyDoctors.length];

    await tx
      .insert(emergencyCases)
      .values({
        id: deterministicUuid("emergency", caseId),
        caseId,
        patientId: ctx.patients.get(plan.patientId)!,
        doctorId: ctx.staff.get(doctorStaffId) ?? null,
        arrivalTime,
        triageLevel: scenario.triageLevel,
        status,
        chiefComplaint: scenario.chiefComplaint,
        diagnosis: status === "Waiting" ? null : scenario.diagnosis,
        treatment: status === "Waiting" ? null : scenario.treatment,
        notes: "Recorded during emergency triage (demo data).",
        createdAt: arrivalTime,
        updatedAt: arrivalTime,
      })
      .onConflictDoUpdate({
        target: emergencyCases.caseId,
        set: {
          patientId: ctx.patients.get(plan.patientId)!,
          doctorId: ctx.staff.get(doctorStaffId) ?? null,
          arrivalTime,
          triageLevel: scenario.triageLevel,
          status,
          chiefComplaint: scenario.chiefComplaint,
          diagnosis: status === "Waiting" ? null : scenario.diagnosis,
          treatment: status === "Waiting" ? null : scenario.treatment,
          updatedAt: new Date(),
        },
      });
  }

  return { emergencyCases: total };
}

/** 14 surgeries across the catalogue with a status mix. */
export async function seedSurgeries(
  tx: Tx,
  ctx: SeedContext
): Promise<SeedCounts> {
  const rng = createRng(0x5029e1);
  const now = ctx.now;
  const statuses = [
    "Completed", "Completed", "Scheduled", "Completed", "Post-Op",
    "Scheduled", "Completed", "Cancelled", "Completed", "Scheduled",
    "Completed", "Scheduled", "Completed", "Scheduled",
  ];
  const planPool = ctx.plans.filter((p) => p.admitted || p.discharged);

  const total = statuses.length;
  for (let i = 0; i < total; i++) {
    const surgeryId = `SRG-${pad3(i + 1)}`;
    const procedure =
      SURGERY_CATALOG[i % SURGERY_CATALOG.length];
    const status = statuses[i];
    const isPast = status === "Completed" || status === "Post-Op";
    const surgeryDate = isPast
      ? daysFrom(now, -2 - Math.floor(rng() * 34))
      : daysFrom(now, 1 + Math.floor(rng() * 28));
    if (status === "Cancelled" && surgeryDate < now) {
      surgeryDate.setTime(daysFrom(now, 3).getTime());
    }

    const surgeon =
      ctx.doctors.find((d) => d.department === procedure.department) ??
      ctx.doctors.find((d) => d.name) ??
      ctx.doctors[0];
    const plan = planPool[i % planPool.length];

    await tx
      .insert(surgeries)
      .values({
        id: deterministicUuid("surgery", surgeryId),
        surgeryId,
        patientId: ctx.patients.get(plan.patientId)!,
        surgeonId: ctx.staff.get(surgeon.staffId)!,
        procedureName: procedure.procedureName,
        procedureType: procedure.procedureType,
        surgeryDate,
        estimatedDuration: procedure.estimatedDuration,
        operatingRoom: `OR-${1 + (i % 4)}`,
        department: procedure.department,
        status,
        preOpNotes:
          isPast || status === "Scheduled"
            ? "Pre-operative assessment complete. Fasting advised."
            : null,
        postOpNotes:
          status === "Completed"
            ? "Procedure completed uneventfully. Stable in recovery."
            : status === "Post-Op"
              ? "Post-op day 1: wound clean, vitals stable."
              : null,
        complications: status === "Completed" && i % 5 === 0 ? "Nil" : null,
        anesthesiaType: procedure.anesthesiaType,
        notes: "Scheduled through the surgery planning workflow (demo data).",
        createdAt: daysFrom(surgeryDate, -10),
        updatedAt: daysFrom(surgeryDate, -10),
      })
      .onConflictDoUpdate({
        target: surgeries.surgeryId,
        set: {
          patientId: ctx.patients.get(plan.patientId)!,
          surgeonId: ctx.staff.get(surgeon.staffId)!,
          procedureName: procedure.procedureName,
          procedureType: procedure.procedureType,
          surgeryDate,
          estimatedDuration: procedure.estimatedDuration,
          operatingRoom: `OR-${1 + (i % 4)}`,
          department: procedure.department,
          status,
          preOpNotes:
            isPast || status === "Scheduled"
              ? "Pre-operative assessment complete. Fasting advised."
              : null,
          postOpNotes:
            status === "Completed"
              ? "Procedure completed uneventfully. Stable in recovery."
              : status === "Post-Op"
                ? "Post-op day 1: wound clean, vitals stable."
                : null,
          anesthesiaType: procedure.anesthesiaType,
          updatedAt: new Date(),
        },
      });
  }

  return { surgeries: total };
}

/** Notifications for the five demo accounts (ids resolved at runtime). */
export async function seedNotifications(
  tx: Tx,
  ctx: SeedContext
): Promise<SeedCounts> {
  const now = ctx.now;
  const emailByRecipient: Record<string, string> = {
    admin: "admin@medcore.com",
    doctor: "doctor@medcore.com",
    nurse: "nurse@medcore.com",
    reception: "reception@medcore.com",
    pharmacy: "pharmacy@medcore.com",
  };

  const total = NOTIFICATION_SEEDS.length;
  for (let i = 0; i < total; i++) {
    const seed = NOTIFICATION_SEEDS[i];
    const email = emailByRecipient[seed.recipient];
    const recipientId = ctx.users.get(email);
    if (!recipientId) continue;
    const createdAt = hoursFrom(daysFrom(now, -(i % 10)), -(i % 8));
    const isRead = i % 3 !== 0;
    await tx
      .insert(notifications)
      .values({
        id: deterministicUuid("notification", `${email}|${seed.title}|${i}`),
        recipientId,
        title: seed.title,
        message: seed.message,
        type: seed.type,
        isRead,
        readAt: isRead ? createdAt : null,
        action: seed.action ?? null,
        createdAt,
      })
      .onConflictDoUpdate({
        target: notifications.id,
        set: {
          recipientId,
          title: seed.title,
          message: seed.message,
          type: seed.type,
          isRead,
          readAt: isRead ? createdAt : null,
          action: seed.action ?? null,
          createdAt,
        },
      });
  }

  return { notifications: total };
}
